services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coletivogloma-backend
    ports:
      - "80:80"
      - "443:443" 
    environment:
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - NAME_DB=${NAME_DB}
      - OPENCAGE_API_KEY=${OPENCAGE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - URL_DATABASE=${URL_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MAIL_FROM=${MAIL_FROM}
      - NODE_ENV=${NODE_ENV}
      - BUCKET=${BUCKET}
    volumes:
      - logs:/app/logs

volumes:
  logs:
